#!/usr/bin/env bash
# second line always a comment.

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.holberton.online/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    mode http
    balance roundrobin
    server web-server-1 127.0.0.1:80 check